### ISSUE TITLE
favicon for main glcwra page

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/ORA#22]
https://glcwra.wim.usgs.gov/ tries to load the favicon over http:// - switch to https://

Kathy this page is a storymap template - ping Mitch if you need help!

**Comment by ChadFanguy-usgs** [comment]
In the browser devtools I see it loading the favicon from usgs:
    <link rel="shortcut icon" type="image/ico" href="http://www.usgs.gov/favicon.ico" />
